repos:
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.13.7
- repo: local
  hooks:
    - id: lint-staged
      name: lint-staged
      entry: npx lint-staged
      language: system
      pass_filenames: false
      stages: [pre-commit]
    - id: commitlint
      name: commitlint
      entry: npx --no -- commitlint --edit
      language: system      
      stages: [commit-msg]
      

